<!DOCTYPE html>
<html lang="id">
  <head>
  <?= render('head') ?>
  </head>
  <body>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header mdl-layout--fixed-drawer">
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <span class="mdl-layout-title">Akun</span>
        </div>
      </header>
      <?= render('drawer') ?>
      <main class="mdl-layout__content">
        <div class="mdlx-data-list">
          <?php foreach ($items as $item): ?>
            <div class="mdlx-data-list__item">
              <span style="float:right;"><?= format_number($item->balance) ?></span>
                <a href="../transaction/?accountId=<?= $item->id ?>">
                  <?= e($item->name) ?>
                </a>
            </div>
          <?php endforeach ?>
        </div>
      </main>
    </div>
    <?= render('foot') ?>
  </body>
</html>
