<!DOCTYPE html>
<html lang="id">
  <head>
    <?= render('head') ?>
    <style>
      .g {color:green;}.r{color:red;}
    </style>
  </head>
  <body>
    <form method="POST" class="mdl-layout mdl-js-layout mdl-layout--fixed-header mdl-layout--fixed-drawer">
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <span class="mdl-layout-title">Transaksi</span>
          <div class="mdl-layout-spacer"></div>
          <a class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect"
             href="./editor?accountId=<?= $filter['accountId'] ?>"><i class="material-icons left">add</i></a>
          <button class="mdl-button mdl-button--icon mdl-js-button mdl-js-ripple-effect" id="filter-button" type="button">
            <i class="material-icons">filter_list</i>
          </button>
        </div>
      </header>
      <?= render('drawer') ?>
      <main class="mdl-layout__content">
        <div class="mdlx-data-list">
          <div class="mdlx-data-list__item" style="background:#eee;">
            <div style="float:right;text-align:right;">
              <span><b><?= format_number($lastBalance) ?></b></span>
            </div>
            <div><b>SALDO AKHIR</b></div>
          </div>
          <?php $balance = $lastBalance ?>
          <?php foreach ($items as $item): ?>
          <?php
            $balanceAfter = $balance;
            $balanceBefore = $balance - $item->amount;
          ?>
            <div class="mdlx-data-list__item">
              <a href="./editor?id=<?= $item->id ?>">
              <div style="float:right;text-align:right;">
                <?php if ($filter['accountId'] == -1): ?>
                  <div style="font-size:12px;line-height:1.2em;"><?= e($item->accountName) ?></div>
                <?php endif ?>
                <div class="<?= $item->amount > 0 ? 'g' : 'r' ?>"><b><?= ($item->amount > 0 ? '+' : '') . format_number($item->amount) ?></b></div>
                <div style="font-size:12px;line-height:1.2em;"><?= format_number($balanceAfter) ?></div>
              </div>
              <div style="font-size:12px;line-height:1.4em;">
                  <div><b><?= e($item->categoryName) ?></b></div>
                  <div><?= to_locale_datetime($item->dateTime) ?></div>
                  <div>#<?= $item->id ?> - <?= e($item->username) ?></div>
                  <div><i><?= e($item->description) ?></i></div>
              </div>
              </a>
            </div>
          <?php $balance -= $item->amount ?>
          <?php endforeach ?>
          <div class="mdlx-data-list__item" style="background:#eee;">
            <div style="float:right;text-align:right;">
              <span><b><?= format_number($balance) ?></b></span>
            </div>
            <div><b>SALDO AWAL</b></div>
          </div>
        </div>
      </main>
    </form>
    <form method="GET">
      <dialog id="filter-dialog" class="mdl-dialog">
        <h4 class="mdl-dialog__title">Penyaringan</h4>
        <div class="mdl-dialog__content">
          <div class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label" style="width:100%;">
            <select class="mdl-selectfield__select" id="accountId" name="accountId">
              <option value="-1">Semua Akun</option>
              <?php foreach ($accounts as $account): ?>
                <option value="<?= $account->id ?>" <?= $account->id == $filter['accountId'] ? 'selected' : '' ?>>
                  <?= e($account->name) ?>
                </option>
              <?php endforeach ?>
            </select>
            <label class="mdl-selectfield__label" for="categoryId">Akun</label>
          </div>
          <div class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label" style="width:100%;">
            <select class="mdl-selectfield__select" id="categoryId" name="categoryId">
              <option value="-1">Semua Kategori</option>
              <?php foreach ($categories as $category): ?>
                <option value="<?= $category->id ?>" <?= $category->id == $filter['categoryId'] ? 'selected' : '' ?>>
                  <?= e($category->name) ?>
                </option>
              <?php endforeach ?>
            </select>
            <label class="mdl-selectfield__label" for="categoryId">Kategori</label>
          </div>
          <div class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label" style="width:100%;">
            <select id="date" name="date" class="mdl-selectfield__select">
              <option value="today" <?= $filter['date'] === 'today' ? 'selected' : '' ?>>Hari Ini</option>
              <option value="-1" <?= $filter['date'] === '-1' ? 'selected' : '' ?>>Kemarin</option>
              <option value="-2" <?= $filter['date'] === '-2' ? 'selected' : '' ?>>2 hari ke belakang</option>
              <option value="-3" <?= $filter['date'] === '-3' ? 'selected' : '' ?>>3 hari ke belakang</option>
              <option value="-4" <?= $filter['date'] === '-4' ? 'selected' : '' ?>>4 hari ke belakang</option>
              <option value="-5" <?= $filter['date'] === '-5' ? 'selected' : '' ?>>5 hari ke belakang</option>
              <option value="-6" <?= $filter['date'] === '-6' ? 'selected' : '' ?>>6 hari ke belakang</option>
              <option value="-7" <?= $filter['date'] === '-7' ? 'selected' : '' ?>>7 hari ke belakang</option>
              <option value="thisweek" <?= $filter['date'] === 'thisweek' ? 'selected' : '' ?>>Minggu Ini</option>
              <option value="prevweek" <?= $filter['date'] === 'prevweek' ? 'selected' : '' ?>>Minggu Kemarin</option>
              <option value="thismonth" <?= $filter['date'] === 'thismonth' ? 'selected' : '' ?>>Bulan Ini</option>
              <option value="prevmonth" <?= $filter['date'] === 'prevmonth' ? 'selected' : '' ?>>Bulan Kemarin</option>
            </select>
            <label class="mdl-selectfield__label" for="date">Tanggal</label>
          </div>
        </div>
        <div class="mdl-dialog__actions">
          <button type="submit" class="mdl-button apply">OK</button>
          <button type="button" class="mdl-button close">batal</button>
        </div>
      </dialog>
    </form>
    <?= render('foot') ?>
    <script>
      confirmOnClick('#delete-button', 'Hapus akun?');
      setupStandardFilterDialog();
    </script>
  </body>
</html>